# Generated by Django 2.2.6 on 2022-10-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221014_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscriptions',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_and_user_are_different',
        ),
    ]
